"""obligations: debts and conversion priorities

Revision ID: 08383e9b6268
Revises: 856184c5e474
Create Date: 2026-08-03 09:39:23.048135
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.database
from alembic import op

revision: str = "08383e9b6268"
down_revision: str | None = "856184c5e474"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obligation_fundings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sa.Integer(), nullable=False),
        sa.Column("amount_nzd", app.database.MoneyText(length=30), nullable=False),
        sa.Column("conversion_id", sa.Integer(), nullable=True),
        sa.Column("funded_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_obligation_fundings")),
    )
    with op.batch_alter_table("obligation_fundings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_obligation_fundings_obligation_id"), ["obligation_id"], unique=False
        )

    op.create_table(
        "obligations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("obligation_type", sa.String(length=32), nullable=False),
        sa.Column("total_nzd", app.database.MoneyText(length=30), nullable=False),
        sa.Column("amount_funded_nzd", app.database.MoneyText(length=30), nullable=False),
        sa.Column("remaining_override_nzd", app.database.MoneyText(length=30), nullable=True),
        sa.Column("annual_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("interest_basis", sa.String(length=16), nullable=False),
        sa.Column("daily_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("earliest_payment_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("relationship_importance", sa.String(length=16), nullable=False),
        sa.Column("minimum_payment_nzd", app.database.MoneyText(length=30), nullable=True),
        sa.Column("partial_allowed", sa.Boolean(), nullable=False),
        sa.Column("target_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("max_wait_days", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("archived_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_obligations")),
    )
    with op.batch_alter_table("obligations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_obligations_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligations_completed"), ["completed"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligations_priority"), ["priority"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obligations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_obligations_priority"))
        batch_op.drop_index(batch_op.f("ix_obligations_completed"))
        batch_op.drop_index(batch_op.f("ix_obligations_active"))

    op.drop_table("obligations")
    with op.batch_alter_table("obligation_fundings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_obligation_fundings_obligation_id"))

    op.drop_table("obligation_fundings")
    # ### end Alembic commands ###
