"""alerts: rules, tranche state and notification log

Revision ID: 856184c5e474
Revises: a5812016795e
Create Date: 2026-08-01 08:52:22.119430
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.database
from alembic import op

revision: str = "856184c5e474"
down_revision: str | None = "a5812016795e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("services", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("queued", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("suppressed_reason", sa.String(length=120), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("delivered_at", app.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
    )
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.create_index("ix_notification_log_created", ["created_at"], unique=False)

    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("threshold", app.database.RateText(length=34), nullable=True),
        sa.Column("comparison", sa.String(length=16), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_triggered_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("notification_targets", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_alert_rules_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    with op.batch_alter_table("alert_rules", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_rules_strategy_type", ["strategy_id", "rule_type"], unique=False
        )

    op.create_table(
        "tranche_alert_states",
        sa.Column("tranche_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("qualifying_samples", sa.Integer(), nullable=False),
        sa.Column("first_qualifying_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("last_sample_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("last_sample_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("last_notified_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("notification_count", sa.Integer(), nullable=False),
        sa.Column("near_notified_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("reset_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tranche_id"],
            ["tranches.id"],
            name=op.f("fk_tranche_alert_states_tranche_id_tranches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tranche_id", name=op.f("pk_tranche_alert_states")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tranche_alert_states")
    with op.batch_alter_table("alert_rules", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_rules_strategy_type")

    op.drop_table("alert_rules")
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.drop_index("ix_notification_log_created")

    op.drop_table("notification_log")
    # ### end Alembic commands ###
