"""strategies: tranches, requirements, conversions

Revision ID: a5812016795e
Revises: e8b5124e0c0d
Create Date: 2026-08-01 08:37:09.554205
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.database
from alembic import op

revision: str = "a5812016795e"
down_revision: str | None = "e8b5124e0c0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("initial_source_amount", app.database.MoneyText(length=30), nullable=False),
        sa.Column("funds_available_amount", app.database.MoneyText(length=30), nullable=False),
        sa.Column("funds_arrival_date", app.database.UTCDateTime(), nullable=True),
        sa.Column("strategy_start_date", app.database.UTCDateTime(), nullable=True),
        sa.Column("final_deadline", app.database.UTCDateTime(), nullable=True),
        sa.Column("minimum_acceptable_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("walk_away_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("require_targets_in_order", sa.Boolean(), nullable=False),
        sa.Column("fee_model_id", sa.Integer(), nullable=True),
        sa.Column("rate_provider_id", sa.String(length=32), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("archived_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.database.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fee_model_id"], ["fee_models.id"], name=op.f("fk_strategies_fee_model_id_fee_models")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategies_status"), ["status"], unique=False)

    op.create_table(
        "deadline_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("due_date", app.database.UTCDateTime(), nullable=False),
        sa.Column("required_source_amount", app.database.MoneyText(length=30), nullable=True),
        sa.Column("required_percentage", app.database.MoneyText(length=30), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_deadline_requirements_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deadline_requirements")),
    )
    op.create_table(
        "tranches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("allocation_type", sa.String(length=16), nullable=False),
        sa.Column("allocation_value", app.database.MoneyText(length=30), nullable=False),
        sa.Column("calculated_source_amount", app.database.MoneyText(length=30), nullable=False),
        sa.Column("target_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("minimum_rate", app.database.RateText(length=34), nullable=True),
        sa.Column("deadline", app.database.UTCDateTime(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("intended_for_auto_conversion", sa.Boolean(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("wise_auto_conversion_reference", sa.String(length=128), nullable=True),
        sa.Column("target_first_reached_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("notification_sent_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("acknowledged_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_tranches_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tranches")),
    )
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tranches_strategy_sequence", ["strategy_id", "sequence"], unique=False
        )

    op.create_table(
        "conversions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("tranche_id", sa.Integer(), nullable=True),
        sa.Column("source_amount", app.database.MoneyText(length=30), nullable=False),
        sa.Column("target_amount", app.database.MoneyText(length=30), nullable=False),
        sa.Column("gross_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("effective_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("fee_source_currency", app.database.MoneyText(length=30), nullable=True),
        sa.Column("fee_target_currency", app.database.MoneyText(length=30), nullable=True),
        sa.Column("fee_total_target_equivalent", app.database.MoneyText(length=30), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_transaction_id", sa.String(length=128), nullable=True),
        sa.Column("executed_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("record_source", sa.String(length=16), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("receipt_filename", sa.String(length=200), nullable=True),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_conversions_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tranche_id"],
            ["tranches.id"],
            name=op.f("fk_conversions_tranche_id_tranches"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversions")),
    )
    with op.batch_alter_table("conversions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversions_executed_at"), ["executed_at"], unique=False
        )
        batch_op.create_index(
            "ix_conversions_provider_txn", ["provider", "provider_transaction_id"], unique=False
        )
        batch_op.create_index(
            "ix_conversions_strategy_executed", ["strategy_id", "executed_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversions", schema=None) as batch_op:
        batch_op.drop_index("ix_conversions_strategy_executed")
        batch_op.drop_index("ix_conversions_provider_txn")
        batch_op.drop_index(batch_op.f("ix_conversions_executed_at"))

    op.drop_table("conversions")
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.drop_index("ix_tranches_strategy_sequence")

    op.drop_table("tranches")
    op.drop_table("deadline_requirements")
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategies_status"))

    op.drop_table("strategies")
    # ### end Alembic commands ###
