"""rates: samples, aggregates, provider status, fee models

Revision ID: e8b5124e0c0d
Revises: edbfa0d34aba
Create Date: 2026-08-01 08:19:19.411189
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.database
from alembic import op

revision: str = "e8b5124e0c0d"
down_revision: str | None = "edbfa0d34aba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fee_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("fee_type", sa.String(length=32), nullable=False),
        sa.Column("fixed_fee", app.database.MoneyText(length=30), nullable=False),
        sa.Column("percentage_fee", app.database.MoneyText(length=30), nullable=False),
        sa.Column("minimum_fee", app.database.MoneyText(length=30), nullable=True),
        sa.Column("maximum_fee", app.database.MoneyText(length=30), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("effective_from", app.database.UTCDateTime(), nullable=True),
        sa.Column("effective_to", app.database.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_models")),
    )
    op.create_table(
        "manual_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", app.database.RateText(length=34), nullable=False),
        sa.Column("entered_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_rates")),
    )
    op.create_table(
        "provider_status",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("last_success_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("last_failure_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("failing_since", app.database.UTCDateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_latency_ms", sa.Integer(), nullable=True),
        sa.Column("retry_after", app.database.UTCDateTime(), nullable=True),
        sa.Column("updated_at", app.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("provider", name=op.f("pk_provider_status")),
    )
    op.create_table(
        "rate_aggregates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("bucket", sa.String(length=8), nullable=False),
        sa.Column("bucket_start", app.database.UTCDateTime(), nullable=False),
        sa.Column("open_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("high_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("low_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("close_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("average_rate", app.database.RateText(length=34), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("created_at", app.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_aggregates")),
    )
    with op.batch_alter_table("rate_aggregates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rate_aggregates_bucket",
            ["source_currency", "target_currency", "bucket", "bucket_start"],
            unique=True,
        )

    op.create_table(
        "rate_samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("source_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", app.database.RateText(length=34), nullable=False),
        sa.Column("rate_numeric", sa.Float(), nullable=False),
        sa.Column("quote_type", sa.String(length=24), nullable=False),
        sa.Column("provider_timestamp", app.database.UTCDateTime(), nullable=True),
        sa.Column("retrieved_at", app.database.UTCDateTime(), nullable=False),
        sa.Column("expires_at", app.database.UTCDateTime(), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("raw_reference", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_samples")),
    )
    with op.batch_alter_table("rate_samples", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rate_samples_pair_time",
            ["source_currency", "target_currency", "retrieved_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_rate_samples_provider_time", ["provider", "retrieved_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rate_samples_rate_numeric"), ["rate_numeric"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rate_samples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_samples_rate_numeric"))
        batch_op.drop_index("ix_rate_samples_provider_time")
        batch_op.drop_index("ix_rate_samples_pair_time")

    op.drop_table("rate_samples")
    with op.batch_alter_table("rate_aggregates", schema=None) as batch_op:
        batch_op.drop_index("ix_rate_aggregates_bucket")

    op.drop_table("rate_aggregates")
    op.drop_table("provider_status")
    op.drop_table("manual_rates")
    op.drop_table("fee_models")
    # ### end Alembic commands ###
